[loggers]
keys=root,default,sql_solutions, pandas_solutions

[handlers]
keys=timedRotatingHandler

[formatters]
keys=fileFormatter

[logger_root]
level=INFO
handlers=timedRotatingHandler
qualname=root
propagate=0

[logger_default]
level=INFO
handlers=timedRotatingHandler
qualname=default
propagate=0

[logger_sql_solutions]
level=INFO
handlers=timedRotatingHandler
qualname=sql_solutions
propagate=0

[logger_pandas_solutions]
level=INFO
handlers=timedRotatingHandler
qualname=pandas_solutions
propagate=0

[handler_timedRotatingHandler]
class=handlers.TimedRotatingFileHandler
level=INFO
formatter=fileFormatter
args=('%(filename)s','midnight',1,7,"utf-8")

[formatter_fileFormatter]
format=%(asctime)s | %(levelname)s | %(filename)s | %(lineno)s | %(name)s | Msg:%(message)s
datefmt=%Y-%m-%d_%H:%M
